### PR TITLE
check-install missing packages

### PR DESCRIPTION
**Pull request by HichamMourad**
Check it out please Will.  Let me know. 
Thanks. h.

### CODE REVIEW

**Review by willtome — CHANGES_REQUESTED** [review]
When installing subscription manager, I think that should go after we set the hostname otherwise we remove the repos needed to install it. Also, please set the state to `present` or `installed`.

yum-utils looks good to me.

**Comment by HichamMourad** [comment]
I've made the changes.

**Review by willtome — CHANGES_REQUESTED** [review]
@HichamMourad the subscription manager tasks needs to move up around line 19 after the `set hostname` task and before the `remove rhui client packages` task

**Review by willtome — APPROVED** [review]
Closes #62

**Pull request merged**
