### PR TITLE
Bump ansible.controller version

### LINKED ISSUE #59: Warnings in requirements for latest AAP
Getting the below warning on latest AAP

[WARNING]: You are running collection version 4.1.1 but connecting to Red Hat
Ansible Automation Platform version 4.3.1

### PR DESCRIPTION
**Pull request by MKletz**
Resolves #59

### CODE REVIEW

**Review by willtome — CHANGES_REQUESTED** [review]
Can you bump the following collections as well? These are the latest published. We will test with these and roll a new EE too if there are no issues.

Thanks
 
controller_config -> 2.2.5
rhel_system_roles -> 1.20.0
community.general -> 6.3.0
community.podman -> 1.10.1
choco -> 1.4.0
community.windows -> 1.12.0
ansible.windows -> 1.13.0
azcollection -> 1.14.0
amazon.aws -> 5.2.0
satellite -> 3.8.0

**Comment by MKletz** [comment]
@willtome done, choco and podman where already unpinned

**Comment by willtome** [comment]
Controller needs to be set to 4.3.0. There is no 4.3.1 on AH

**Comment by MKletz** [comment]
Corrected

**Review by willtome — APPROVED** [review]

**Pull request merged**
