### PR TITLE
RHEL9 Provisioning

### PR DESCRIPTION
**Pull request by willtome**

### CODE REVIEW

**Comment by willtome** [comment]
TODO: not enough RHEL9 images to pull latest-2

**Comment by benblasco** [comment]
Do we need to run through a full test of all the Linux and cloud demo content to verify everything works well with RHEL 9 as well?  I looked at your code change, and assuming that the regexp you used to find a relevant RHEL 9 image is correct, then there's not much else to review!

**Comment by willtome** [comment]
That's probably a good idea @benblasco. I'll run through tests and report back here

**Comment by willtome** [comment]
Tested:

- [x] Linux / Register with Insights
- [x] Linux / Patching
- [x] LINUX / Install Web Console (cockpit)
- [x] LINUX / Troubleshoot
- [x] LINUX / Temporary Sudo
- [x] LINUX / System Roles
- [x] LINUX / Stop Service
- [x] LINUX / Start Service
- [x] LINUX / Podman Webserver
- [ ] LINUX / Compliance Enforce - STIG for RHEL9 still in draft
- [ ] LINUX / Insights Compliance Scan - STIG for RHEL9 still in draft

**Comment by willtome** [comment]
@benblasco I think we are good to merge without compliance since it is still in draft for RHEL9

**Comment by benblasco** [comment]
I am comfortable with that.  Should we create a placeholder issue for the RHEL 9 compliance scan and enforce?  Furthermore the Insights compliance scan is not dependent on STIG specifically as it will do whatever you have configured in console.redhat.com

**Review by benblasco — APPROVED** [review]
Very simple changes, and ultimately we are dependent on all the demo cases working to validate the RHEL 9 updates.

**Pull request merged**
